import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'
import { readFileSync } from 'node:fs'

// The component sidebar + nav groups are generated by scripts/gen-pages.mjs.
// Read defensively so a bare `vitepress` invocation (before `docs:gen`) still boots.
function readGenerated<T>(rel: string, fallback: T): T {
  try {
    const url = new URL(rel, import.meta.url)
    return JSON.parse(readFileSync(fileURLToPath(url), 'utf8')) as T
  } catch {
    return fallback
  }
}

const componentSidebar = readGenerated('./components.sidebar.json', [] as any[])

// GitHub Pages base path. Override with DOCS_BASE for other hosts (e.g. "/").
const base = process.env.DOCS_BASE ?? '/lucent/'

export default defineConfig({
  title: 'Lucent',
  description:
    'A complete, beautiful glassmorphic React component set that stays truly lightweight — with runtime-adjustable transparency for accessibility.',
  lang: 'en-US',
  base,
  cleanUrls: true,
  lastUpdated: true,
  head: [
    ['meta', { name: 'theme-color', content: '#0a0e1a' }],
    ['meta', { name: 'color-scheme', content: 'dark light' }],
  ],
  themeConfig: {
    logo: undefined,
    nav: [
      { text: 'Guide', link: '/guide/introduction' },
      { text: 'Theming', link: '/guide/theming' },
      { text: 'Components', link: '/components/' },
      { text: 'Publishing', link: '/guide/publishing' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'CSS Import', link: '/guide/css-import' },
          ],
        },
        {
          text: 'Core Concepts',
          items: [
            { text: 'Theming & Runtime Controls', link: '/guide/theming' },
            { text: 'Transparency & Solid Mode', link: '/guide/transparency' },
            { text: 'Portal Theming', link: '/guide/portal-theming' },
            { text: 'Reduced Motion', link: '/guide/reduced-motion' },
            { text: 'RTL Support', link: '/guide/rtl' },
            { text: 'SSR & Next.js', link: '/guide/ssr' },
          ],
        },
        {
          text: 'Release',
          items: [{ text: 'Publishing & Packaging', link: '/guide/publishing' }],
        },
      ],
      '/components/': componentSidebar,
    },
    search: { provider: 'local' },
    socialLinks: [{ icon: 'github', link: 'https://github.com/orionshub/lucent' }],
    outline: { level: [2, 3] },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Lucent — glassmorphic React components',
    },
  },
  vite: {
    // Native esbuild JSX for the React example islands — no @vitejs/plugin-react
    // dev-preamble coupling, works identically in dev and SSR build.
    esbuild: { jsx: 'automatic', jsxImportSource: 'react' },
    resolve: {
      dedupe: ['react', 'react-dom'],
    },
    optimizeDeps: {
      include: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'],
    },
    ssr: {
      // Keep the library out of the SSR externalization path so its ESM +
      // "use client" boundaries resolve cleanly during static rendering.
      noExternal: ['@orionshub/lucent'],
    },
  },
})
